# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00e1f47c146c5d466e065b3c0d3dacc6e30f2c7cabd7b002ce936287914457b7541863877e2c5c8d29bbedfe24fda0819a3430a318ceb6d1adfdc522fa9ea38a

test:
  secret_key_base: 59508bc07dff8e1345186973b4fba30317c94c97aa81f8b0b6e9c7d862edb367646a78248e5fc75010e0ddca863c1d77adbd55f5a230c233bc9fedcf7ad33a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
